name: qutip-tutorials
channels:
  - conda-forge
dependencies:
  - python==3.10.4
  - pip==22.1.2
  - scipy==1.11.2
  - matplotlib==3.5.2
  - imagemagick==7.1.0_36
  - mpmath==1.2.1
  - qutip==4.7.3
  - cython==0.29.32
  - notebook==6.4.11
  - jupytext==1.13.8
  - pip:
      - qutip-qip==0.3.0
      - numpy==1.25.2
